name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust: "1.95"  # MSRV - can't use variables here.
            args: --exclude mitmproxy-linux-ebpf
          - os: macos-latest
            rust: "1.95"  # MSRV - can't use variables here.
            args: --exclude mitmproxy-linux-ebpf
          - os: ubuntu-22.04
            rust: "1.95"  # MSRV - can't use variables here.
            args: --exclude mitmproxy-linux-ebpf
          - os: ubuntu-latest
            rust: stable
            args: --exclude mitmproxy-linux-ebpf
          - os: ubuntu-latest  # old Ubuntu to test eBPF verifier compatibility
            rust: nightly
            args: --package mitmproxy-linux-ebpf
    env:
      RUSTFLAGS: ${{ matrix.rust == 'nightly' && '-Zpanic_abort_tests -C panic=abort' || '' }}
    steps:
      - uses: mhils/workflows/checkout@5b6540d578f48644ffa5e955cedadc81034cb7d8  # v18.0
      - uses: ./.github/actions/setup
        with:
          rust-version: ${{ matrix.rust }}

      - name: Run "cargo check"
        # the action-rs/cargo action adds inline annotations for "cargo check" output
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          toolchain: ${{ matrix.rust }}
          command: check
          args: --workspace --verbose ${{ matrix.args }}
      - if: matrix.rust != 'nightly'  # XXX: weird errors here
        name: Run "cargo test"
        # the action-rs/cargo action adds inline annotations for "cargo test" output
        uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72
        with:
          toolchain: ${{ matrix.rust }}
          command: test
          args: --workspace --verbose ${{ matrix.args }}
      - if: matrix.os == 'ubuntu-22.04'  # Test that eBPF loads
        run: cargo test --features root-tests
        working-directory: mitmproxy-linux
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER: sudo -E

  build:
    strategy:
      matrix:
        include:
          - name: windows-x86_64
            os: windows-latest
          - name: linux-x86_64
            os: ubuntu-latest
            args: --compatibility manylinux2014 --zig --sdist
          - name: linux-arm64
            os: ubuntu-24.04-arm
            args: --compatibility manylinux2014 --zig
          - name: macos-universal
            os: macos-latest
            target: aarch64-apple-darwin x86_64-apple-darwin
            args: --target universal2-apple-darwin
    runs-on: ${{ matrix.os }}
    name: build mitmproxy-rs (${{ matrix.name }})
    steps:
      - uses: mhils/workflows/checkout@5b6540d578f48644ffa5e955cedadc81034cb7d8  # v18.0
      - uses: ./.github/actions/setup
        with:
          extra-targets: ${{ matrix.target }}

      - if: runner.os == 'Linux'
        name: Install maturin[zig] from PyPI
        uses: install-pinned/maturin-with-zig@7f54e6144d8fd17188d0e99742fefc4bcb178e06
      - if: runner.os != 'Linux'
        name: Install maturin from PyPI
        uses: install-pinned/maturin@3bfd83cd34bdcbcc8a10e459c2a9e41e6c33e706

      - run: maturin build --release ${{ matrix.args }}
        working-directory: ./mitmproxy-rs

      # ensure that sdist is building.
      # We do this here instead of a separate job because we don't want to wait for the entire matrix.
      - if: contains(matrix.args, 'sdist')
        run: pip install --no-dependencies target/wheels/*.tar.gz

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: wheels-${{ matrix.name }}
          path: target/wheels

  check:
    if: always()
    needs:
      - test
      - build
    uses: mhils/workflows/.github/workflows/alls-green.yml@5b6540d578f48644ffa5e955cedadc81034cb7d8  # v18.0
    with:
      jobs: ${{ toJSON(needs) }}

